# config.yaml

ssh:
  host: 222.114.170.35
  port: 22
  username: pyh
  password: '1234'

transfer:
  local_path: D:\goorm\FinalProject\goorm_final_pjt\transfer\test.txt
  remote_path: /home/pyh/Desktop/test.txt
