# config.yaml

# 인덱스 이름 (기본적으로 날짜가 붙은 형식으로 생성되지만, 원하는 경우 직접 지정할 수 있습니다)
index_name: "malware-analysis"

# Kibana URL
kibana_url: "http://3.36.50.236:5601"

# Elasticsearch URL
elasticsearch_url: "http://3.36.50.236:9200"

# HTTP 헤더 (Kibana API 호출 시 필요)
headers:
  kbn-xsrf: "true"
  Content-Type: "application/json"

# 인덱스 패턴 제목 (Kibana 데이터 뷰 생성 시 사용)
index_pattern_title: "malware-analysis"

# 데이터 뷰 고유 ID (옵션 - 미리 정의된 ID가 있다면 사용, 없으면 빈 값으로 두세요)
data_view_id: "malware-data-view"
